export enum RouterNameEnum {
  ADMIN_BASE_LAYOUT = 'ADMIN_BASE_LAYOUT',
  ADMIN_HOME_LAYOUT = 'ADMIN_HOME_LAYOUT',
  ADMIN_HOME_MAIN = 'ADMIN_HOME_MAIN',

  GENERAL_BASE_LAYOUT = 'ADMIN_BASE_LAYOUT',
  GENERAL_HOME_LAYOUT = 'ADMIN_HOME_LAYOUT',
  GENERAL_HOME_MAIN = 'ADMIN_HOME_MAIN',
}
