export enum RouterNameEnum {
  AUTH_BASE_LAYOUT = 'AUTH_BASE_LAYOUT',
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_BUSINESS_LOGIN = 'AUTH_BUSINESS_LOGIN',
  AUTH_BUSINESS_ADMIN_LOGIN = 'AUTH_BUSINESS_ADMIN_LOGIN',


  MY_BASE_LAYOUT = 'MY_BASE_LAYOUT',
  MY_MAIN = 'MY_MAIN',

  ADMIN_BASE_LAYOUT = 'ADMIN_BASE_LAYOUT',
  ADMIN_HOME_LAYOUT = 'ADMIN_HOME_LAYOUT',
  ADMIN_HOME_MAIN = 'ADMIN_HOME_MAIN',

  GENERAL_BASE_LAYOUT = 'GENERAL_BASE_LAYOUT',
  GENERAL_HOME_LAYOUT = 'GENERAL_HOME_LAYOUT',
  GENERAL_HOME_MAIN = 'GENERAL_HOME_MAIN',
}
